[package]
name = "gela"
version = "0.1.0"
edition = "2024"
authors = ["Joona Aalto <jondolf.dev@gmail.com>"]
description = "Generic linear algebra with wide SIMD support"
repository = "https://github.com/Jondolf/gela"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "math", "matrix", "vector", "quaternion"]
categories = ["game-engines"]

[features]
default = []

# Enables approximate equality comparisons with `approx`
approx = ["dep:approx"]

# Enables arbitrary structured value generation with `arbitrary`
arbitrary = ["dep:arbitrary"]

# Enables validation of archived types with `bytecheck`
bytecheck = ["rkyv/bytecheck"]

# Enables casting types to and from bytes with `bytemuck`
bytemuck = ["dep:bytemuck"]

# Enables alignment of types to match CUDA requirements
cuda = []

# Enables writing types into and reading them from GPU buffers with `encase`
encase = ["dep:encase"]

# Enables conversion to and from mint interoperability types
mint = ["dep:mint"]

# Enables nightly portable_simd support
portable_simd = ["gnum/portable_simd", "bytemuck?/nightly_portable_simd"]

# Enables random sampling of types with `rand`
rand = ["dep:rand"]

# Enables serialization and deserialization with `rkyv`
rkyv = ["dep:rkyv"]

# Enables serialization and deserialization with `serde`
serde = ["dep:serde_core"]

# Enables serialization and deserialization with `speedy`
speedy = ["dep:speedy"]

# Enables casting types to and from bytes with `zerocopy`
zerocopy = ["dep:zerocopy", "dep:zerocopy-derive"]

[dependencies]
gnum = { path = "../gnum", features = ["portable_simd"] }

# Optional dependencies for features
approx = { version = "0.5", optional = true, default-features = false }
arbitrary = { version = "1.4.2", optional = true, default-features = false }
bytemuck = { version = "1", optional = true, default-features = false, features = [
    "aarch64_simd",
    "wasm_simd",
] }
encase = { version = "0.12", optional = true, default-features = false }
mint = { version = "0.5.8", optional = true, default-features = false }
rand = { version = "0.10", optional = true, default-features = false }
rkyv = { version = "0.8", optional = true, default-features = false }
serde_core = { version = "1.0", optional = true, default-features = false }
speedy = { version = "0.8", optional = true, default-features = false }
zerocopy = { version = "0.8", optional = true, default-features = false, features = [
    "simd",
] }
zerocopy-derive = { version = "0.8", optional = true, default-features = false }

[dev-dependencies]
# For now, we use portable_simd here, will be removed later
gela = { path = ".", features = ["portable_simd"] }

# For testing the implementations of optional dependencies
rkyv = { version = "0.8", default-features = false, features = ["alloc"] }
serde_json = "1.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_arch, values("spirv"))',
] }
