[package]
name = "gela"
version = "0.1.0-alpha.1"
edition = "2024"
authors = ["Joona Aalto <jondolf.dev@gmail.com>"]
description = "Generic linear algebra for games and graphics"
repository = "https://github.com/Jondolf/gela"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = [
    "gamedev",
    "math",
    "matrix",
    "vector",
    "quaternion",
    "simd",
    "determinism",
]
categories = ["mathematics", "game-engines", "no-std"]

[features]
default = ["std", "wide"]

# Enables using the standard library's math routines instead of portable approximations
std = [
    "gnum/std",
    "gimd?/std",
    "approx?/std",
    "rand?/std",
    "rkyv?/std",
    "serde_core?/std",
    "zerocopy?/std",
]

# Enables SIMD support on stable Rust using `wide`
wide = ["simd", "gimd/wide"]

# Enables SIMD support on nightly Rust using `core::simd`
portable_simd = [
    "simd",
    "gnum/portable_simd",
    "gimd/portable_simd",
    "bytemuck?/nightly_portable_simd",
]

# Internal, implied by `wide` and `portable_simd`
simd = ["dep:gimd"]

# Enables approximate equality comparisons with `approx`
approx = ["dep:approx"]

# Enables generation of arbitrary values with `arbitrary`
arbitrary = ["dep:arbitrary", "std"]

# Enables validation of archived types with `bytecheck`
bytecheck = ["rkyv/bytecheck"]

# Enables casting types to and from bytes with `bytemuck`
bytemuck = ["dep:bytemuck", "gimd?/bytemuck"]

# Enables alignment of types to match CUDA requirements
cuda = []

# Enables writing types into and reading them from GPU buffers with `encase`
encase = ["dep:encase", "std"]

# Enables conversion to and from mint interoperability types
mint = ["dep:mint"]

# Enables random sampling of types with `rand`
rand = ["dep:rand"]

# Enables serialization and deserialization with `rkyv`
rkyv = ["dep:rkyv"]

# Enables serialization and deserialization with `serde`
serde = ["dep:serde_core"]

# Enables serialization and deserialization with `speedy`
speedy = ["dep:speedy", "std"]

# Enables casting types to and from bytes with `zerocopy`
zerocopy = ["dep:zerocopy", "dep:zerocopy-derive", "gimd?/zerocopy"]

[dependencies]
gnum = { version = "0.1.0-alpha.1", default-features = false }
gimd = { version = "0.1.0-alpha.1", optional = true, default-features = false }

# Optional dependencies for features
approx = { version = "0.5", optional = true, default-features = false }
arbitrary = { version = "1.4.2", optional = true, default-features = false }
bytemuck = { version = "1", optional = true, default-features = false, features = [
    "aarch64_simd",
    "derive",
    "wasm_simd",
] }
encase = { version = "0.12", optional = true, default-features = false }
mint = { version = "0.5.8", optional = true, default-features = false }
rand = { version = "0.10", optional = true, default-features = false }
rkyv = { version = "0.8", optional = true, default-features = false }
serde_core = { version = "1.0", optional = true, default-features = false }
speedy = { version = "0.8", optional = true, default-features = false }
zerocopy = { version = "0.8", optional = true, default-features = false, features = [
    "simd",
] }
zerocopy-derive = { version = "0.8", optional = true, default-features = false }

[dev-dependencies]
# For testing the implementations of optional dependencies
rkyv = { version = "0.8", default-features = false, features = ["alloc"] }
serde_json = "1.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_arch, values("spirv"))',
] }
